apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ov9ox3ct0-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:e182788f7bf6125c20d28f84d086a2553f03f3ed@sha256:50efc854a718be0047383893e5f02a4b2e401b3cc6996acfe768fcfb8c79ccde
          name: container-image
